# Generated by Django 5.1.4 on 2025-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={"verbose_name": "FoodItem", "verbose_name_plural": "FoodItems"},
        ),
    ]
