# Generated by Django 5.1.4 on 2025-12-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_fooditem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={"verbose_name": "FoodItem", "verbose_name_plural": "Food items"},
        ),
    ]
