# Generated by Django 5.1.4 on 2025-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_fooditem_options"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("vendor", "category_name", "slug"),
                name="unique_vendor_category_name_slug",
            ),
        ),
    ]
