# Generated by Django 5.1.4 on 2025-12-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_category_unique_vendor_category_name_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_vendor_category_name_slug",
        ),
    ]
