# Generated by Django 5.1.4 on 2025-12-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_remove_category_unique_vendor_category_name_slug"),
        ("vendor", "0008_alter_vendor_vendor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="vendor.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fooditems",
                to="menu.category",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fooditems",
                to="vendor.vendor",
            ),
        ),
    ]
